---
- name: Configure Jumpbox
  hosts: jumpbox
  become: true
  gather_facts: no
  vars_files:
    - '{{global_config_file}}'
  tasks:
  - name: Wait 300 seconds for the nodes to be ready
    wait_for_connection:
      timeout: 300
  - name: Gather facts for first time
    setup:
  - name: "Ensure SSH AllowTcpForwarding is enabled"
    lineinfile:
        state: present
        dest: /etc/ssh/sshd_config
        regexp: "^#AllowTcpForwarding|^AllowTcpForwarding"
        line: 'AllowTcpForwarding yes'
  - name: restart sshd
    service:
      name: sshd 
      state: restarted
  - name: update packages for security
    become: true
    yum:
      name: '*'
      state: latest
#      exclude: kernel*,kmod*,amlfs*

- name: Join AD domain and mount anfhome
  hosts: scheduler, ondemand, grafana
  become: true
  gather_facts: no
  vars_files:
    - '{{global_config_file}}'

  tasks:
  - name: Wait 300 seconds for the nodes to be ready
    wait_for_connection:
      timeout: 300
  - name: Gather facts for first time
    setup:

  - name: setup private domain if not set in resolv.conf
    shell: |
      if ! grep -q {{domain_name}} /etc/resolv.conf; then
        sed -i 's/search /search {{domain_name}} /' /etc/resolv.conf
        # Stop NetworkManager overwriting /etc/resolv.conf
        cat > /etc/NetworkManager/conf.d/90-dns-none.conf << EOF
        [main]
        dns=none
      EOF
      fi

  - name: Read Password from KV
    command: az keyvault secret show --vault-name {{key_vault}} -n {{admin_user}}-password --query "value" -o tsv
    delegate_to: localhost
    connection: local
    register: password
    become: false
    run_once: true

  - name: Join domain
    include_role:
      name: domain_join
    vars:
      domain_admin: "{{admin_user}}"
      domain_password: "{{password.stdout}}"
      domain: "{{domain_name}}"
      # domain_primary_dns: "{{primary_dns}}"
      # domain_secondary_dns: "{{secondary_dns}}"
      domain_homedir: "{{homedir_mountpoint}}"
      domain_mount_ip: "{{anf_home_ip}}"
      domain_mount_path: "{{anf_home_path}}"
      domain_mount_opts: "{{anf_home_opts}}"

  - name: Update ANF chmod mode
    file:
      path: '{{homedir_mountpoint}}'
      state: directory
      mode: '0755'
    run_once : true

